piVersion: apps/v1
kind: Deployment
metadata:
name: db-deployment
namespace: <YOUR NAMESPACE>
labels:
app: db
spec:
replicas: <REPLICAS>
strategy:
type: Recreate
minReadySeconds: 20
selector:
matchLabels:
app: db
template:
metadata:
labels:
app: db
spec:
containers:
 - envFrom:
 - secretRef:
 name: db-secret
 name: db-deployment
 image: harbor.dev.afsmtddso.com/devopsbootcamplab02/db:971c881-dcbc818
 ports:
 - containerPort: 5432

